# Generated by Django 5.2.8 on 2025-11-17 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=64, unique=True)),
                ('subject', models.CharField(blank=True, max_length=256)),
                ('topic', models.CharField(blank=True, max_length=128)),
                ('initiated_by', models.CharField(blank=True, max_length=32)),
                ('order_id', models.CharField(blank=True, max_length=64)),
                ('product', models.CharField(blank=True, max_length=128)),
                ('messages', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_summary', models.TextField(blank=True)),
                ('draft_fields', models.JSONField(blank=True, default=dict)),
                ('edited_summary', models.TextField(blank=True)),
                ('edited_fields', models.JSONField(blank=True, default=dict)),
                ('approved_summary', models.TextField(blank=True)),
                ('approved_fields', models.JSONField(blank=True, default=dict)),
                ('state', models.CharField(choices=[('DRAFTED', 'Drafted'), ('EDITED', 'Edited'), ('APPROVED', 'Approved')], default='DRAFTED', max_length=16)),
                ('approver', models.CharField(blank=True, max_length=128)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='core.thread')),
            ],
        ),
    ]
